### PR TITLE
ARM OSX Migrator 2

### PR DESCRIPTION
**Pull request by duncanmmacleod**
This PR closes #20 with a fix to set `GSSAPI_SUPPORT_DETECT=false` when cross compiling.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dhirschfeld** [comment]
LGTM! If this passes CI are you happy for this to be merged @duncanmmacleod?

**Comment by duncanmmacleod** [comment]
> LGTM! If this passes CI are you happy for this to be merged @duncanmmacleod?

Absolutely! I don't 100% understand the implications of the `GSSAPI_SUPPORT_DETECT` variable, but if you're happy, I'm happy.

**Comment by dhirschfeld** [comment]
> *I don't 100% understand the implications of the `GSSAPI_SUPPORT_DETECT` variable*

I'm no expert, but I figure if we get bug reports we can always revert.

**Comment by duncanmmacleod** [comment]
@dhirschfeld, in a naïve attempt to address the travis issues I have moved the linux aarch builds onto azure, I hope that doesn't break anything...

**Comment by dhirschfeld** [comment]
CI passes, but I'm not sure we're supposed to directly edit the CI files ourselves. I think the idea is that you're supposed to specify things in [`conda-forge.yml`](https://conda-forge.org/docs/maintainer/infrastructure.html#using-azure-for-everything), re-render and conda-smithy will make the necessary changes.

In any case, this is well above my pay-grade so I'm going to call in the big-guns (ping @conda-forge/core!) to say how this should be done.

**Comment by duncanmmacleod** [comment]
@dhirschfeld, sorry, I should have been clearer. I _did_ only manually edit `conda-forge.yml` and then squashed in the changes from the conda-smithy regenerator.

**Comment by dhirschfeld** [comment]
Ah right. I guess it's good to merge then!

**Pull request merged**
